version: '3.8'
services:
  student_management:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=lab09
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1234567
      - MYSQL_PASSWORD=1234567
    ports:
      - '3336:3306'
volumes:
  db:
    driver: local